# Generated by Django 2.1 on 2021-10-03 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import food.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(default=food.models.create_random_id, max_length=24, unique=True, verbose_name='article id')),
                ('name', models.CharField(db_index=True, default='', max_length=100, verbose_name='The name of the food')),
                ('description', models.TextField(default='', verbose_name='food description')),
                ('ingredient_list', models.CharField(default='', max_length=200, verbose_name='Raw material table')),
                ('image', models.ImageField(blank=True, null=True, upload_to=food.models.food_article_image_upload_path, verbose_name='cover')),
                ('author', models.CharField(db_index=True, default='', max_length=100, verbose_name='author')),
                ('like', models.IntegerField(default=0, verbose_name='Like count')),
                ('fav', models.IntegerField(default=0, verbose_name='Favorite count')),
                ('click_number', models.IntegerField(default=0, verbose_name='clicks')),
                ('tips', models.TextField(default='', verbose_name='tips')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added at')),
            ],
            options={
                'verbose_name': 'food article',
                'verbose_name_plural': 'food article',
                'db_table': 'food_article',
            },
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=food.models.create_random_id, max_length=50, verbose_name='Image name')),
                ('image', models.ImageField(blank=True, upload_to=food.models.food_image_upload_path, verbose_name='Food picture')),
                ('like', models.IntegerField(default=0, verbose_name='Number of likes')),
                ('fav', models.IntegerField(default=0, verbose_name='number of favorites')),
                ('click_number', models.IntegerField(default=0, verbose_name='clicks')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
            ],
            options={
                'verbose_name': 'Food picture',
                'verbose_name_plural': 'Food picture',
                'db_table': 'food_images',
            },
        ),
        migrations.CreateModel(
            name='FoodIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='The name of the ingredients')),
                ('dosage', models.CharField(max_length=20, verbose_name='Food amount')),
                ('classification', models.CharField(choices=[('1', 'Main ingredients'), ('2', 'Accessories'), ('3', 'Ingredients')], default='1', max_length=10, verbose_name='Food classification')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added at')),
                ('article_id', models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, to='food.FoodArticle', to_field='article_id', verbose_name='article name')),
            ],
            options={
                'verbose_name': 'Foodstuffs',
                'verbose_name_plural': 'Foodstuffs',
                'db_table': 'food_ingredients',
            },
        ),
        migrations.CreateModel(
            name='FoodSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=0, verbose_name='Prep step sequence number')),
                ('description', models.TextField(default='', verbose_name='Prep step description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=food.models.food_article_step_image_upload_path, verbose_name='picture of step')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added at')),
                ('article_id', models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, to='food.FoodArticle', to_field='article_id', verbose_name='Article name')),
            ],
            options={
                'verbose_name': 'Food preparation steps',
                'verbose_name_plural': 'Food preparation steps',
                'db_table': 'food_steps',
            },
        ),
        migrations.CreateModel(
            name='ImageTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=20, verbose_name='Picture tag')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added at')),
            ],
            options={
                'verbose_name': 'Picture tag',
                'verbose_name_plural': 'Picture tag',
                'db_table': 'food_imagestags',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='label')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added at')),
            ],
            options={
                'verbose_name': 'Food labels',
                'verbose_name_plural': 'Food labels',
                'db_table': 'food_tags',
            },
        ),
        migrations.AddField(
            model_name='foodimage',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, to='food.ImageTags', verbose_name='Image labels'),
        ),
        migrations.AddField(
            model_name='foodarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, to='food.Tags', verbose_name='labels'),
        ),
    ]
